{% set name = "cli-ui" %}
{% set version = "0.16.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cli-ui-{{ version }}.tar.gz
  sha256: 97feef6664be4441a15430726c39f7c19a1f84c3bdea65c8ec70662fc57f7006

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry
  run:
    - colorama >=0.4.1
    - python >=3.7,<4.0
    - tabulate >=0.8.3
    - unidecode >=1.0.23

test:
  imports:
    - cli_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmerejkowsky/python-cli-ui
  summary: Build Nice User Interfaces In The Terminal
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
