{% set name = "cli-ui" %}
{% set version = "0.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cli-ui-{{ version }}.tar.gz
  sha256: 57fefcc7187329031c84c9262548decc48ab94a13798ea90a99c760cd9b302c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - colorama >=0.4.1
    - python >=3.6,<4.0
    - tabulate >=0.8.3
    - unidecode >=1.0.23

test:
  imports:
    - cli_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dmerejkowsky/python-cli-ui
  summary: Build Nice User Interfaces In The Terminal
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmerejkowsky
    - umonaca
